---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Open access data for transport research: tools, modelling and simulation (OpenInfra)

# Introductory sentence

<!-- try to get to the bottom of your research in one sentence, this is your elevator pitch. -->

## Project overview

<!---Sticking to one paragraph (3-4 sentences) give the background of the project including project aims. Is there anything new or unique about this research? --->

Dependence on motor modes of travel has been associated with adverse physical, mental, and environmental health (reference 1)(image 1). A shift towards a more sustainable - active - transport, such as walking, wheeling, and cycling might help to tackle health problems (reference 2). However, to encourage the uptake of active modes of travel, it is important to meet the infrastructural needs of citizens. For this, citizen participation in the planning process is essential. A potential way to foster engagement is to encourage citizens to generate data of their local communities which, consequently, could be used make local context and data informed decisions. In this case, open crowd-sourced data might become invaluable. Given this, the project aims to explore how open crowd-sourced data, specifically OpenStreetMap(OSM) data, can be used to *understand*, *prioritise*, and *design* active travel infrastructure. 

## Data and methods

<!-- Outline the; who, what, when, where and how of the study.. -->

OSM data is open, thus free to use regardless of the purpose as long as the source is credited. To query OSM database, an `osmextract` package (reference 3) in R has been used. Three metropolitan counties - West Yorkshire, Greater Manchester, and Merseyside - and an administrative area - Greater London - have been chosen as case studies in the first 6 months of the project with a goal to scale it up to the entire England in months 7-12. 

Moreover, it is important to understand the data structure of OSM in order to utilize it. Essentially, OSM data is composed of three key elements: nodes, ways, and relations. To describe geographic features, *tags*, or key=value pairs, are utilized. For more details on each of the aspects, read an [introductory article](https://udsleeds.github.io/openinfra/articles/openinfra.html) written on the subject matter as part of the project.

To explore OSM data, exploratory data analysis (EDA) was applied. EDA was used to understand the potential and limitations of the OSM data. Bar charts have been chosen as a visual tool to demonstrate the presence/absence of data. In particular, bar charts in this report are used to present the proportions of (some of) the tags relevant to active transport research to all the mapped highways in a given case study. The size of data per area can be seen in Table 1. It is important to note that OSM data is constantly being updated, hence the size of data might fluctuate depending on when it was downloaded.

The project has a [GitHub repository](https://github.com/udsleeds/openinfra) with an aim to promote the reproducibility of project outputs. In order to encourage engagement with OSM data, a [website](https://udsleeds.github.io/openinfra/articles/openinfra.html) has been developed which currently contains two articles: one introducing OSM data from a theoretical point of view and another one demonstrates how to download and start working with OSM data in R.

## Key findings

<!-- Outline the results of the research project. Aim to stick to 2-3 paragraphs. Use imagery (clearly labelled) where appropriate.. -->

The analysis of the chosen areas has shown that footways and cycleways constitute about 1/3 of all the mapped highways in OSM. Greater London stands out as the proportion reaches 1/2 mark (Table 2). This is not surprising given London's investment in active travel (reference 4). Surprisingly, however, Greater Manchester has very similar network proportion to other two metropolitan counties even though it has, in 2018, proposed an ambition to deliver the most comprehensive active travel network in the England (reference 5). <!---Also, it is important to note that, for example, footways in OSM take a specific semantic meaning - representing minor pathways - thus do not reflect an entire pedestrian network. As a result, it is likely that more comprehensive --->

Arguably the most important characteristic of OSM is not its ability to represent various highways but rather attributes about them. For example, it is possible to refine `highway=footway` tag using `footway` tag to indicate that it is a sidewalk rather than a crossing (coded as "other" in Table 2). Nevertheless, given the high proportion of mapped footways, it is surprising that not many of them are refined to permit a better understanding of the highway network. This is not only limited to footways but cycleways as well (see Table 3), thus limiting the applicability of OSM data in transport, and specifically active travel, research.

The lack of data is especially evident in the highway features relevant for accessible infrastructure planning.

## Value of the research

<!-- What is the impact, how will this benefit xyz? How could the research be applied to real-world problems or what is the usage/benefit? -->

It is essential to meet the needs of citizens if active travel is to become a primary modal choice. OpenInfra project explores 

Value of research:
- focus on accessibility
- explore the limitations and benefits of OSM in transport research, specifically accessible infrastructure planning
- improve the the accessibility of OSM data -> vignettes, functions, etc

## Quote from project partner 

<!--  “One sentence or two approved by an industry partner or collaborator.” Include name, job title and organisation.-->

## Insights


- OSM has a great potential to become a go-to (open) dataset in the accessible infrastructure planning.
- Currently OSM does not live up to its potential because of the missing information on the specifics of a highway that are essential for accessible infrastructure planning.

## Research theme

Urban analytics

## People

<!-- Who was involved, their job title and institution. -->


## Funders

This work was supported by the ESRC funded Consumer Data Research Centre (CDRC) under grant references ES/S007164/1 and ES/L011891/1.

## Images + o

Please send a couple of high res images that can be used for the case study (e.g. graph, visualisation).

links:

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/523460/Working_Together_to_Promote_Active_Travel_A_briefing_for_local_authorities.pdf

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1033990/net-zero-strategy-beis.pdf





