---
title: "OSM for sustainable transport planning"
format: html
editor: source
bibliography: sotm2022.bib
csl: apa-numeric-brackets.csl
---
**Abstract (10-100 words)**

OpenStreetMap (OSM) data has the potential to facilitate bottom-up approach to transport planning which is essential for localized data-driven policy interventions. Given this, OpenInfra project is exploring the potential of OSM data in transport research with a focus on active travel. The exploration showed that currently missing data limits the applicability of OSM data. Nevertheless, we argue that the potential and relevance of OSM data can be demonstrated by recategorizing OSM data to provide more actionable insights to policy-makers. This, therefore, could encourage the uptake of open data leading to more transparent, reproducible, and participatory transport planning. 

**Extended abstract (800-1200 words)**

One of the key domains in which OpenStreetMap (OSM) data has been utilized is transport planning [@arsanjani_etal2015]. OSM has been used in agent-based transport simulation [@ziemke_etal2019] and routing [@luxen_vetter2011], including cycling [@yeboah_alvanides_2015], walking [@zielstra_hochmair2012], wheeling [@neis2015], and blind pedestrian routing [@cohen_dalyot_2021]. Another application of OSM data is to support evidence-based investment in sustainable transport infrastructure. In a recent (2021) paper Nelson et al. [-@nelson_etal2021] argue that OSM has the potential to become a primary source of data on infrastructure across the globe. 

Regardless of OSM’s potential to become a primary source of data on transport infrastructure in general, its potential in active travel infrastructure planning is yet to be realised. One of the reasons behind this lag might be linked to the perceived unreliability of open-access crowdsourced data [@basiri_etal2019] and the fact that planning for active travel requires high resolution and rich data, e.g. sidewalk widths, geometries and surface roughness data. The quality of OSM has received extensive examination [@arsanjani_etal2015] in which the question concerning data completeness plays a significant role because, it is argued, the mappers are not coordinated to guarantee systematic coverage [@Haklay2010]. To address this issue, Barrington-Leigh and Millard-Ball [-@leigh_ball_2017] assessed OSM road completeness and found that globally over 80% of roads are mapped. Problematically, their assessment focused on roads designed for motor traffic, thus excluding other modes of transport. This gap has been partially addressed by Ferster et al. [-@ferster_etal2020] who examined and compared OSM cycling infrastructure in Canada. They have not, however, considered the infrastructure from the perspective of accessibility. Moreover, there seems to exist no equivalent study using OSM data in the context of pedestrian infrastructure planning. 

Nevertheless, open-access crowdsourced data, such as OSM, can support increasing demand for local evidence to inform transport policies. This is important in the context of countries such as the UK, which has bold walking and cycling targets: 50% of trips made by walking and cycling in towns and cities by 2030 [@gear_change_2020]. Such targets require a shift in transport planning, away from provision for motorised modes towards more sustainable active modes of travel, such as walking, wheeling, and cycling [@netzero2021]. The importance of localising interventions to meet the needs of local communities has been outlined in both policy [@ltn2020, @inclusive_mobility_dft_2021] and academic papers [@Aldred_etal_2016]. An increase in citizen engagement in the decision-making could be achieved through the encouragement of "produsage" -- a model in which citizens both produce and use data [@boularouk_etal_2017]. 

Acknowledging the potential of OSM to boost citizen participation, OpenInfra project, run at the University of Leeds (UK), aims to address the gap concerning the potential OpenStreetMap in transport research. The project started by examining the existing OSM tags relevant to active travel infrastructure in England with a focus on West Yorkshire, Greater Manchester, Greater London, and Merseyside. The data was imported using `osmextract` [@Gilardi_Lovelace2021], an R package, and explored using a range of exploratory data analysis (EDA) techniques. Reproducible code that generates all the figures presented here can be found on GitHub: https://github.com/udsleeds/openinfra/tree/main/sotm2022

Given the extensive use of OSM data in transport research, it is not surprising that OSM provides a comprehensive active travel network, yet there is a lack of specification concerning the type of infrastructure that is present (e.g. is it a cycle lane or a cycle track?). For instance, cycleways and footways constitute about 1/3 of all the mapped highways on which one can legally walk, wheel or cycle but only a few percent of the cycleways and footways have tags detailing their type. The data gets even scarcer in the context of accessible infrastructure planning. For example, there is a lot of missing information on the presence and type of kerbs -- a street element that might make the movement of a wheelchair user more challenging [@timaite_etal2022]. 

The missing data currently limits the use of OSM data in active travel planning, however this does not mean that the use of OSM data should be dismissed. Following Nelson et al.'s [-@nelson_etal2021] argument that it is important to make crowdsourced data more actionable, we decided to recategorise OSM data based on the Inclusive Mobility (IM) [@inclusive_mobility_dft_2021], a guide that outlines the best practices in creating inclusive pedestrian infrastructure in the UK. For this, a function has been written (documentation: https://udsleeds.github.io/openinfra/articles/im_get.html). It takes an OSM dataframe, recategorises its tags based on the definitions outlined in the guide and returns an OSM dataframe with new columns to use in further analysis. However, the function provides a simplification of the IM guide for a couple of reasons. The first one could be considered in terms of definitional discrepancies. For instance, the guide defines footways as "pavements adjacent to roads", yet this is not easily extracted from the OSM in which `highway=footway` is a generic tag and often there is no further refinement (e.g., `sidewalk=*`) to determine if it is a pavement adjacent to a road. Another reason is linked to assigned values. For example, the guide identifies six tactile paving surfaces but OSM focuses on the presence/absence of tactile paving, thus limiting how much information can be extracted from the data. 

One potential application of the IM function could be to explore the existence and geographic distribution of accessibility indicators, such as the presence of footways, footpaths, or kerbs (see Figure 1). Yet, more interesting results can be produced by using recategorised OSM data in conjunction with other datasets that would help to improve the understanding of street accessibility. As an illustration for this, an open-access Leeds Central Council Footfall data was used [@footfall_data2021]. We reasoned that the locations at which footfall data was collected are heavily used by pedestrians, thus demonstrating the need to ensure inclusivity of spaces. 5 unique streets were identified, which resulted in 35 linestrings in OSM. Then, a basic index of accessibility, defined by 5 indicators, was created. If a street meets all 5 requirements, it receives a maximum index of 5; for every missing indicator the score is dropped by 1. For example, if a linestring classifies as a footway, footpath, or implied footway based on the IM guide then it receives +1. If it also has an even surface, it receives an additional +1, thus totaling to +2. If none of the other conditions are met then the final index score is 2. Following this, 19 out of 35 mapped linestrings scored 2 while the rest had an index of 1. This example does not necessarily show that the streets are inaccessible because the missing data make it hard to make a fair judgement (e.g., in this case not a single linestring has data on kerbs). However, we would argue that this is a space for OSM to produce more readily actionable insights regarding transport infrastructure, especially if joined with other (open) datasets that would help to overcome some of its current data limitations. 

The following steps of the OpenInfra project are focused on scaling up. The goal is to produce ‘OSM transport infrastructure data packs’ for transport authorities in the UK to support the uptake of open-access data, such as OSM, in transport planning. We believe that our project and other efforts to make OSM data more ‘analysis ready’ for transport planners will make the process of transport planning more transparent, reproducible, and participatory. Increased use of OSM data by practitioners could lead to a positive feedback loop in which more people contribute to OSM, further raising the profile. Indeed, with sustained financial and political support, the uptake of and social investment in crowdsourced data such as OSM could lead to more evidence-based and therefore more effective investment in sustainable transport infrastructure and, ultimately, more active travel with large health and environmental benefits [@gear_change_2020]. OSM specifically has the potential to provide localised insights on the existing transport infrastructure and facilitate more inclusive and accessible transport planning.







